### ISSUE TITLE
Add option to set and update attributes

### ISSUE THREAD

**Issue by yep-dev** [shannonhochkins/ha-component-kit#77]
**Is your feature request related to a problem? Please describe.**
I need a way to set and update attributes on some entities.

**Describe the solution you'd like**
- `setAttributes` method set or to change just some of them, but because HA requires resending state with all attributes, it would pass the same state (ensuring it's the newest one first so it doesn't break), but can change attributes like `setState` by just passing its object, or to update them (also he newest data) by passing the function `(oldAttributes) => newAttributes`
- adding same object/function attributes param (also as  to setValue, setOption, etc – low priority if above is already implemented, but sometimes you want to update both state and attributes

**Describe alternatives you've considered**
Well, I can patch on something myself just good enough to achieve this, but that probably wouldn't be in line with the existing architecture/style/plans of the project.

**Additional context**
My HA is getting quite complex and some things make sense being bundled in the attributes.

**Comment by shannonhochkins** [comment]
My primary focus right now is building the addon for HA, however this can only be achieved via the rest api rather than Web sockets, I suggest you get something working at past, and then provide me some instructions and code examples of what you've done and I'll integrate it fully, sorry but there's a lot of different requests right now, but I feel the most important is the addon for now

**Comment by shannonhochkins** [comment]
I will close this as it's not an issue but rather a feature request - please suggest changes if you get something working!
