### ISSUE TITLE
Setup CLI issues

### ISSUE THREAD

**Issue by yann510** [shannonhochkins/ha-component-kit#85]
**Describe the bug**
1. `useHass must be used within a HassProvider, have you wrapped your application in <HassConnect hassUrl={HASS_URL} />?`
2. There is no deploy script in package.json

**To Reproduce**
Steps to reproduce the behaviour of bug number 1:
1. `npm create hakit@latest`
1. Ensure your token and home-assistant URLs are valid in the `.env` file
1. `npm i`
1. `npm run dev`
1. Notice the first error mentioned

Steps to reproduce the behaviour of bug number 1:
1. `npm create hakit@latest`
1. `npm i`
1. `npm run publish`
1. Notice the first error `Missing script: "deploy"`

**Expected behavior**
After running the creation CLI, I should have a working project ready to go :)

**System Info (please complete the following information):**
 - IDE: Webstorm
 - Browser: chrome
 - npm version: 9
 - node version: 18

**Comment by shannonhochkins** [comment]
Hi mate, you need to run `npm install` followed by `npm run dev`. 

When the wizard asked you, did you include your home assistant url correctly?

Can you publish what you've got to npm so I can review please? Obviously, exclude your .env file and the link to your public home assistant instance.

The first error happens when you attempt to use a component or hook outside of HassConnect

As for the second issue, I'll take a look at that, I may not have included the deploy script correctly but thankyou for reporting it!

**Comment by yann510** [comment]
Thanks for the quick reply. Yes, I had run the `npm install`, and forgot to add it in the repro steps (they are now updated).

Here is the repro code: https://github.com/yann510/home-assistant-dashboard
With the `.env` content:
```
VITE_FOLDER_NAME=home-assistant-dashboard
VITE_HA_URL=http://homeassistant.local:8123
VITE_HA_TOKEN=
VITE_SSH_USERNAME=
VITE_SSH_PASSWORD=
VITE_SSH_HOSTNAME=
```

**Comment by shannonhochkins** [comment]
With HassConnect, when using an insecure url (http) there's an option you must enable, have a look at the docs for HassConnect

This may not be your problem as I do throw an error when a non https url is provided without this flag

Have you ran a console log on the vite import for the HAAS_url inside app.tsx to see if it's coming though?

Is there any other errors in the console? It's 11pm here so I'll have to test this out a bit later, your setup looks correct at a glance, please hold tight I'll get back to you when I can :)

**Comment by shannonhochkins** [comment]
I see the issue, the ThemeProvider must be included within HassConnect, which is most likely a problem with my template not something you've done wrong!

Sorry about that! Just move it inside HassConnect and you should be good to go!

**Comment by yann510** [comment]
That has fixed my issue!! <3
I can create a PR if you'd like.

I guess for the deploy part, all you need to do is add the `deploy.ts` script inside the `package.json` scripts?

**Comment by shannonhochkins** [comment]
Awesome!

You've nudged me to go take another pass at the create script, there's a few things It's missing that I can automate for users, glad to see the typescript sync worked for you too!

I'll sort it all out It's a bit complicated to work with the repository, but if you feel like it, go for it! I'd love the help, been flying solo on this for a long time now, and I have no idea if the developer / contributor docs are up to scratch without prior knowledge, so I wouldn't mind some feedback if you decide to do so!

**Comment by yann510** [comment]
Cool, I'll give it a go today and provide feedback as I explore the repository in more detail, I am glad to help you and this project out :)

**Comment by shannonhochkins** [comment]
Legend! thanks, mate! Honestly, this project can achieve a lot, which makes its learning curve a little steep, but hopefully, my docs and the typescript nature helps you figure everything out :) Happy coding!

**Comment by shannonhochkins** [comment]
Just an FYI - i made some further improvements here as i noticed a few other problems, even once deployed, it never loaded correctly because it was missing the base config value for vite.

https://github.com/shannonhochkins/ha-component-kit/pull/87

Thanks for bringing this all to my attention - hopefully this works well for others going forward!

I've noted all the changes I made after you made yours in the linked PR above
